### PR TITLE
Fix macOS build

### PR DESCRIPTION
**Pull request by nohajc**
I'm not sure what exactly cargo metadata does but https://github.com/stratis-storage/libblkid-rs/commit/609aab40e11fbfcf35088b0f8b18e902c4dcd093 broke my build with linker errors:

```
  Undefined symbols for architecture arm64:
    "_blkid_do_safeprobe", referenced from:
        libblkid_rs::probe::BlkidProbe::do_safeprobe::h99485a5d24512e80 in liblibblkid_rs-0b248e8a09844861.rlib[6](libblkid_rs-0b248e8a09844861.libblkid_rs.7375e6b3ccd5aca0-cgu.03.rcgu.o)
    "_blkid_free_probe", referenced from:
        _$LT$libblkid_rs..probe..BlkidProbe$u20$as$u20$core..ops..drop..Drop$GT$::drop::h629a0bdf7f70e0bf in liblibblkid_rs-0b248e8a09844861.rlib[6](libblkid_rs-0b248e8a09844861.libblkid_rs.7375e6b3ccd5aca0-cgu.03.rcgu.o)
    "_blkid_new_probe_from_filename", referenced from:
        libblkid_rs::probe::BlkidProbe::new_from_filename::hdc4581aa633e0b3c in liblibblkid_rs-0b248e8a09844861.rlib[6](libblkid_rs-0b248e8a09844861.libblkid_rs.7375e6b3ccd5aca0-cgu.03.rcgu.o)
    "_blkid_probe_enable_superblocks", referenced from:
        libblkid_rs::probe::BlkidProbe::enable_superblocks::h0882b0d9c14a8263 in liblibblkid_rs-0b248e8a09844861.rlib[6](libblkid_rs-0b248e8a09844861.libblkid_rs.7375e6b3ccd5aca0-cgu.03.rcgu.o)
    "_blkid_probe_lookup_value", referenced from:
        libblkid_rs::probe::BlkidProbe::lookup_value::h2f0c5f09b46a1fb6 in liblibblkid_rs-0b248e8a09844861.rlib[6](libblkid_rs-0b248e8a09844861.libblkid_rs.7375e6b3ccd5aca0-cgu.03.rcgu.o)
    "_blkid_probe_set_superblocks_flags", referenced from:
        libblkid_rs::probe::BlkidProbe::set_superblock_flags::hfd4187186f358001 in liblibblkid_rs-0b248e8a09844861.rlib[6](libblkid_rs-0b248e8a09844861.libblkid_rs.7375e6b3ccd5aca0-cgu.03.rcgu.o)
  ld: symbol(s) not found for architecture arm64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

So I decided to fix it by partially reverting the offending change. Is it OK to merge it like this?

### CODE REVIEW

**Comment by nohajc** [comment]
Can you explain the purpose of the metadata configuration (or why it needs to be disabled)? I thought the point of pkg-config is to return the correct linker and include paths in any case. So I'm a bit confused.

**Comment by nohajc** [comment]
> Define whether metadata should be emitted for cargo allowing it to automatically link the binary. Defaults to true.

It's not clear to me how the `pkg_config` crate should be used when this is set to false.

**Comment by nohajc** [comment]
I see. Linker paths are not needed for generating the bindings themselves. But I still need the pkg-config paths for my build.

Do I just fix that in my project by adding build.rs with pkg_config or is there a better way?

Maybe if your crate could detect whether cross-compilation is taking place?

**Comment by nohajc** [comment]
@jbaublitz Ok, I changed it so that the `HOST` and `TARGET` environment variables (set by cargo) are compared first.
I believe it is preferable to leave cargo metadata enabled in the most common case if it simplifies building any projects depending on `libblkid-rs`.

**Comment by jbaublitz** [comment]
I apologize for the delay. I was looking into this stuff and apparently, I should be able to add MacOS CI to this crate. That should help me run a few tests to see if I can fix your problem with checking things related to cross-compilation.

**Comment by nohajc** [comment]
It's ok. I think I already solved it. Do you see any problems with my approach of detecting cross-compilation in build.rs and acting accordingly? I don't see why cargo metadata couldn't still be enabled in the default case.

**Comment by jbaublitz** [comment]
I am again a little bit skeptical of the environment variable trick. I don't doubt that it works in most cases, but I'd almost rather have a solution like a feature that allows users to opt in or out of the cargo metadata flag. Ideally I'd like it to just work in both cases (which we may be able to get it to do that if we add additional println statements to build.rs specifying the linking paths from pkg-config) but I'm not sure which would be preferable to you in your case.

**Comment by nohajc** [comment]
But those link path printlns are what you get when you enable metadata as far as I can tell. When they're disabled, pkg-config in build.rs doesn't emit anything.

I'm not sure what additional paths you have in mind. In order to get the correct paths you just need to configure pkg-config properly (e.g. by environment variable overrides in case of cross-compilation).

I don't know the specifics of that particular cross-compilation environment which caused trouble but I still believe cargo metadata does the right thing when HOST and TARGET are the same. Otherwise you need to prepare stuff like rootfs of the target system or possibly even a different pkg-config binary altogether.

I don't see the point of trying to replicate behaviours which are already implemented with the default configuration.

Also, it seems detecting cross-compilation should be fairly reliable because the HOST and TARGET variables are always set by cargo.

**Comment by nohajc** [comment]
Anyway, if you want to make it explicitly configurable, I'd definitely prefer for it to be opt-out.

Generally, my expectation is that if I don't do anything advanced, it should ideally work out of the box with as few configuration knobs as possible.

**Comment by jbaublitz** [comment]
@nohajc Please take a look at #193. The most recent commit is an example of what I'm proposing. I don't see how this is any worse than `.cargo_metadata(true)` and should generally work in both the cross-compilation and non-cross-compilation case.

**Comment by nohajc** [comment]
Isn't this exactly the same thing cargo_metadata already does?

I mean, if pkg-config returns host paths, you'll end up confusing the cross-compilation process all the same.

I don't understand how this solves the issue if you do it unconditionally but frankly I don't understand either what the original cross-compilation issue was.

It could have been a case of misconfiguration of the environment...

**Comment by jbaublitz** [comment]
@nohajc So from my vantage point there is one key difference. My understanding of the issue is that essentially the cargo metadata flag will mix certain target and source flags resulting in broken builds for cross-compilation. Explicitly using the information from the pkg-config library provides a certain amount of separation that essentially allows you to point to the target pkg-config file and use information for the target only. @yhjung0525 What are your thoughts on the above, specifically on whether this is actually reimplementing `.cargo_metadata(true)` or whether this is likely to be more friendly to cross-compilation in environments like Yocto.

**Comment by nohajc** [comment]
I also made another more in-depth comment in #193. I think it would be worth knowing what exactly has gone wrong in that particular environment because to me, it's still generally just about configuring pkg-config for cross-compilation properly (which definitely takes extra work) or not using it at all if you want to do something else with your linker flags.

The notion of mixing host and target paths is even mentioned in pkg-config crate documentation and it's explained as a consequence of misconfiguring pkg-config itself.

I'm not sure how the auto-metadata feature on top of that would cause any more trouble.

**Comment by jbaublitz** [comment]
@nohajc I think the discussion in https://github.com/stratis-storage/devicemapper-rs/issues/965 outlines exactly what went wrong (as in the exact flags that were included from both host and target). I'm willing to potentially revert these changes if we can find a solution for @yhjung0525 to use with pkg-config to fix this problem. I don't have a lot of experience with cross-compilation so if it seems like I'm hesitant to make any changes right now, it's because I want to learn a little bit more about the best solution and implement that so that we can avoid a proliferation of these types of issues moving forward and if it's a user error, I'd like to be able to correct those in the future.

**Comment by nohajc** [comment]
Sure, that's perfectly understandable.

I read the conversation. For me the key piece of information would be why those mixed flags ended up there. Obviously if you disable cargo metadata, pkg-config crate will not emit anything so that's a fine workaround for one cross-compilation scenario but unfortunately it breaks other more conventional scenarios.

For pkg-config to emit suitable paths, it should be enough to configure the correct search path for .pc files so that it doesn't end up reading config files meant for the host system. Isn't it possible that's what happened?

https://docs.rs/pkg-config/latest/pkg_config/#cross-compilation

**Comment by jbaublitz** [comment]
Let's wait a little bit to hear from @yhjung0525 to see if this fixes their problem. If they don't respond in a couple of days, I'll see what I can do to test the cross-compilation case.

**Comment by yhjung0525** [comment]
> Let's wait a little bit to hear from @yhjung0525 to see if this fixes their problem. If they don't respond in a couple of days, I'll see what I can do to test the cross-compilation case.

@jbaublitz 
To address your initial question first: in my current Yocto-based development environment, the build error was resolved by setting `cargo_metadata(false)`.

Here are my thoughts regarding the use of the `pkg-config` crate for library linking in the `devicemapper-sys` crate:

1. I understand that `-sys` crates are expected not only to generate bindings via `bindgen`, but also to support FFI integration, library discovery, and linkage.
2. However, I have doubts about whether the use of `pkg-config` is strictly necessary in this context.
3. While the `pkg-config` crate is primarily intended for use in `build.rs`, its main purpose appears to be configuring native library linkage on the host system.
4. According to the documentation at [https://crates.io/crates/pkg-config](https://crates.io/crates/pkg-config), it is possible to use `pkg-config` for cross-compilation, but only when certain environment variables—such as `PKG_CONFIG_SYSROOT_DIR` and `PKG_CONFIG`—are explicitly set. If these variables are not reliably controlled, using `pkg-config` in a `build.rs` script for cross-compilation may lead to build failures.
5. In version 0.3.1 of `devicemapper-sys`, `pkg-config` is used to configure linkage for `libdevmapper`. However, as mentioned above, if `PKG_CONFIG_SYSROOT_DIR` is not properly set, this may cause builds to fail.

In conclusion, while it's often necessary for a `-sys` crate to support FFI bindings and library discovery, I believe it would be better to adopt a more fine-grained and controllable approach than relying solely on the `pkg-config` crate.

**Comment by nohajc** [comment]
@yhjung0525 Would you agree that leaving cargo_metadata set to true generally makes it easier to use a -sys crate in the common case of host compilation?

Otherwise, when it is disabled, it becomes the responsibility of every crate user to provide linker flags themselves.

Also, and more crucially, does the proposed fix of adding linker flags back in (albeit manually) break your cross-compilation setup again? I would expect so.

**Comment by yhjung0525** [comment]
> @yhjung0525 Would you agree that leaving cargo_metadata set to true generally makes it easier to use a -sys crate in the common case of host compilation?
> 
> Otherwise, when it is disabled, it becomes the responsibility of every crate user to provide linker flags themselves.
> 
> Also, and more crucially, does the fix (#193) of adding linker flags back in (albeit manually) break your cross-compilation setup again? I would expect so.
> 
> This is a different crate but the principle is the same.

@nohajc 
My concern is not specifically about the use of cargo_metadata, but more fundamentally about the use of pkg-config within -sys crates in general.

In my opinion, pkg-config should ideally be used only for configuring the host environment. While it's certainly possible for individual developers to customize pkg-config to provide target-specific linker flags in their own environments, crates published on [crates.io](https://crates.io/) are used in a wide variety of contexts. Given this diversity, it may be worth considering alternative approaches beyond relying solely on pkg-config.

Unfortunately, I don’t have a solid alternative to propose at the moment, but this is my view based on the knowledge and experience I currently have.

**Comment by nohajc** [comment]
@yhjung0525 I understand. Just wanted to clarify if you consider #193 somehow better or if it's still the same issue.

Because it takes the output of pkg-config linker flags and prints it out.

Anyway, I think whether these crates use pkg-config or anything else, it's generally about who should set the linker flags. Whether it's the crate users or if crate authors should attempt auto configuration like this.

I for one think ease of use is important so I would propose to leave cargo_metadata enabled by default and add a feature flag to disable it for advanced use cases like yours.

I was just trying to link to libblkid on macOS which worked fine until this change was introduced.

**Comment by yhjung0525** [comment]
@nohajc 
I understand. Indeed, having the `-sys` crate handle the linker flags can certainly improve usability for many users.

However, since it's unlikely that we can satisfy all environments out of the box, I agree that introducing a feature flag—so users can disable this behavior when necessary—seems like the most practical approach for now.

**Comment by nohajc** [comment]
@mulkieran Sure. I double-checked and everything is working for me with latest master. Thank you!
